version: '3.8'

services:
  web:
    container_name: nextjs-boilerplate
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
